apiVersion: v1
kind: ConfigMap
metadata:
  name: service-version
  namespace: flux-system
data:
  IMAGE_REPOSITORY: docker.io/nuga99
  BACKEND_SERVICE_VERSION: 1.0.0
  CACHE_SERVICE_VERSION: 1.0.0
  DATABASE_SERVICE_VERSION: 1.0.0
  SERVER_SERVICE_VERSION: 1.0.0