---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: server
  namespace: flux-system
spec:
  image: docker.io/nuga99/app_server
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: image-server-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: server
  policy:
    semver:
      range: '>=1.0.0'